name: aurora
description: Widget to easily create aurora gradient backgrounds for your flutter app
version: 1.0.0
homepage: https://github.com/pacifio/aurora

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
